name: Continuous Integration

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: recursive

      - name: Installing dependencies
        run:
          sudo apt update 
          sudo apt install --fix-missing gcc g++ cmake \
          libboost-iostreams-dev libboost-program-options-dev \
          zlib1g-dev
      
      - name: Apply patches to submodules
        run: ./patchGenieutils.sh

      - name: Build
        run:
          mkdir build && cd build
          cmake ..
          cmake --build .
